### ISSUE TITLE
Make Navbar Responsive for Mobile and add a Logo

### ISSUE THREAD

**Issue by Abhiraj-Sardar** [Abhiraj-Sardar/MMS-MusicMadeSimple#1]
![Screenshot 2024-10-05 214544](https://github.com/user-attachments/assets/c1a6eae7-6d22-4759-b9cd-57b729dd10d0)

1. on clicking on this menu button it should display the content of the navbar.
2. add a Logo named MMS that fits well with this background color.

**Comment by South-IN** [comment]
Can I work on this issue ?
And please clarify what should be the logo ?
Would a simple favicon work ?

**Comment by Abhiraj-Sardar** [comment]
Hi @South-IN ,

Yes, you can start working on this issue.

You just need to change the logo text (as shared in the above image) with an image that can be an appropriate logo.
Hint: You can use Logo.ai to generate a logo with Name MMS and add that image to logo section.

Thanks.

**Comment by South-IN** [comment]
Ok can you assign this issue to me ?

**Comment by Abhiraj-Sardar** [comment]
@South-IN Done

**Comment by South-IN** [comment]
@Abhiraj-Sardar I want to know what should be the dimensions of the responsive navbar i.e., 100% width or 50% width or should it take 100% of the height?

**Comment by Abhiraj-Sardar** [comment]
Thank You @South-IN ,

your PR has been merged
