### ISSUE TITLE
Add Styling to Music List

### ISSUE THREAD

**Issue by Abhiraj-Sardar** [Abhiraj-Sardar/MMS-MusicMadeSimple#2]
![{DA5ECAA5-5F26-40D1-8BA6-6FA601717E76}](https://github.com/user-attachments/assets/f2531a33-631b-4629-8512-6f4d95cba630)

add appropriate styling to this list so that it looks good.

**Comment by TEJAS07080** [comment]
@Abhiraj-Sardar can i work on this?

**Comment by Abhiraj-Sardar** [comment]
@TEJAS07080  Sure

**Comment by TEJAS07080** [comment]
i have submitted a pull request regarding the same, kindly review

**Comment by Abhiraj-Sardar** [comment]
Hi @TEJAS07080,

I reviewed the PR. Can you remove the Music Player's Background Color, You only need to style the Music List (the given image area only), not the music background.
 
and in mobile view the music list is not working properly please check it out Thanks for your contribution so far.

**Comment by TEJAS07080** [comment]
@Abhiraj-Sardar Sorry for the misunderstanding, will make the necessary changes asap

**Comment by TEJAS07080** [comment]
@Abhiraj-Sardar as instructed i have reverted back to the original css and just changed the required part and made it mobile responsive, kindly review

**Comment by Abhiraj-Sardar** [comment]
@TEJAS07080 

Your PR is Merged , Thanks For Contributing
