### ISSUE TITLE
Toggle Mode (Light/Dark)

### ISSUE THREAD

**Issue by Abhiraj-Sardar** [Abhiraj-Sardar/MMS-MusicMadeSimple#3]
Add Light and Dark functionality

**Comment by khushiiagrawal** [comment]
i want to work on this issue. Can you assign me this

**Comment by Abhiraj-Sardar** [comment]
@khushiiagrawal Sure

**Comment by Abhiraj-Sardar** [comment]
Great Work @khushiiagrawal , Thanks For Contributing.

**Comment by khushiiagrawal** [comment]
Hey can you also add gssoc-ext label in it 
Thank you
