### ISSUE TITLE
Improve Dark Mode Implementation with Switch Button and Component Logic

### ISSUE THREAD

**Issue by abhayksahu369** [Abhiraj-Sardar/MMS-MusicMadeSimple#9]
# Issue: Dark Mode Functionality Refactor

## Description
The current implementation of the dark mode functionality is handled directly in the `index.html` file. This approach is not ideal as it does not follow React best practices, where functionality should be managed within components.

## Proposed Changes
1. **Refactor Dark Mode Logic**:
   - Move the dark mode functionality from `index.html` to a React component (e.g., `Navbar`).
  
2. **UI Enhancements**:
   - Replace the existing dark mode button with a more intuitive switch button to toggle between light and dark modes.

3. **CSS Updates**:
   - Adjust the CSS to ensure consistent styling and support for the new switch button.

## Benefits
- **Improved Code Structure**: Keeping functionality within components enhances code maintainability and readability.
- **Better User Experience**: A switch button provides a more user-friendly way to toggle themes.

**Comment by abhayksahu369** [comment]
please add the hacktober fest label and assign it to me

**Comment by Abhiraj-Sardar** [comment]
@abhayksahu369 Done

**Comment by abhayksahu369** [comment]
done brother ,please add gssoc-ext label also

**Comment by Abhiraj-Sardar** [comment]
@abhayksahu369 ,
Thanks for Contributing

**Comment by abhayksahu369** [comment]
@Abhiraj-Sardar brother this contribution is still not showing in my gssoc profile 😅 ,I think you need to add level label also ....like level1 , level2 , level3
